### ISSUE TITLE
Changelog, use git-change-log compatible markers

### ISSUE THREAD

**Issue by Thaodan** [poetaster/harbour-tooter#14]
Hey,

Could you do so? This way you get generated changelogs automatically, especially handy for Chum.

See communi for example:
https://build.merproject.org/package/view_file/sailfishos:chum/communi-sailfish/_service:tar_git:harbour-communi.changes?expand=1

**Comment by poetaster** [comment]
Yes. I have a script that yields the relevant entries and have started using it in the one package or the other. The last couple of attempts I got some complaints about dates and have been slacking.

**Comment by Thaodan** [comment]
Mark Washeim ***@***.***> writes:

> Yes. I have a script that yields the relevant entries and have started
Should git-changelog not be enough? If you follow the tag layout you
shouldn't need a separate script.

> using it in the one package or the other. The last couple of attempts
> I got some complaints about dates and have been slacking.

The dates should be fine as long as you keep LC_ALL to C.UTF8 or
en_US.UTF8.

**Comment by poetaster** [comment]
I just tried with -s and -f which works ok, but 'not quite'.  That gives me:

```
1.1.0 / 2022-12-02
==================

  * Forgot an important bit.
  * Added some more debug flags to stop spewing the console.
  * Added self to credits. Added MediaItem display for audio and Integrated MediaItem into MediaBlock/MyMedia elements. Bump release.
  * Add additiona; media element for audio.
  * Merge pull request #16 from cintema/patch-2
  * Merge pull request #15 from cintema/patch-1
  * Update harbour-tooterb.spec
  * Update LoginPage.qml
  * Merge pull request #5 from eson57/patch-2
  * Update harbour-tooterb-sv.ts
```

My script gives me:

```
* Fri Dec 2 11:32:30 2022 +0100 Mark Washeim <blueprint@poetaster.de> 1.1.0

- Forgot an important bit.
- Added some more debug flags to stop spewing the console.
- Added self to credits. Added MediaItem display for audio and Integrated MediaItem into MediaBlock/MyMedia elements. Bump release.
- Add additiona; media element for audio.
- Merge pull request #16 from cintema/patch-2
- Merge pull request #15 from cintema/patch-1
- Update harbour-tooterb.spec
- Update LoginPage.qml
- Merge pull request #5 from eson57/patch-2
- Update harbour-tooterb-sv.ts
```

My script:

```
* Fri Dec 2 11:32:30 2022 +0100 Mark Washeim <blueprint@poetaster.de> 1.1.0
- Forgot an important bit.
- Added some more debug flags to stop spewing the console.
- Added self to credits. Added MediaItem display for audio and Integrated MediaItem into MediaBlock/MyMedia elements. Bump release.
- Add additiona; media element for audio.
- Merge pull request #16 from cintema/patch-2
- Merge pull request #15 from cintema/patch-1
- Update harbour-tooterb.spec
- Update LoginPage.qml
- Merge pull request #5 from eson57/patch-2
- Update harbour-tooterb-sv.ts
```

**Comment by poetaster** [comment]
Ah, I think that should be git-change-log ? And that would require tags for type of work?

**Comment by Thaodan** [comment]
Mark Washeim ***@***.***> writes:

> Ah, I think that should be git-change-log ? And that would require tags for type of work?

Yes you should tag each release git-change-log will pick the difference
between them then.

**Comment by poetaster** [comment]
This is how I'm moving forward. git-change-log now looks like this.

```
* Wed Jan 18 2023 Mark Washeim <blueprint@poetaster.de> - 1.1.4
- [Fix] Home loading and search deduping release
- [Fix] search for tags and persons added header call for max/min and prepend on first call.
- [Issue]: # 26. timelines/home on append uses the link header for min/max id
```
