### ISSUE TITLE
Notifactions don't include the app icon

### ISSUE THREAD

**Issue by Thaodan** [poetaster/harbour-tooter#19]

**Comment by poetaster** [comment]
I just did some testing and took a screenshot.
![Screenshot_20221212_001](https://user-images.githubusercontent.com/1065933/207158579-9f34c1f1-5607-4122-9596-e1ed49eed958.png)

What am I missing? This looks like both types of notification messages have the icon?

**Comment by Thaodan** [comment]
Need to check on this, it might be caused by another app.

**Comment by poetaster** [comment]
Confirmed that this is not the case.
