### ISSUE TITLE
Fresh install via chum missing depenency pyotherside-qml-plugin-python3-qt5

### ISSUE THREAD

**Issue by supremesyntax** [poetaster/harbour-tooter#24]
I've installed via chum and couldn't add an account. Just saw something like "page could not load".
Started via terminal and saw pyotherside module was missing.

Installed pyotherside-qml-plugin-python3-qt5 and it started to work.

I guess you need to add this as a dependency in the spec file.

**Comment by poetaster** [comment]
Thanks for catching it. Included in the upcoming 1.1.2

**Comment by poetaster** [comment]
Corrected in 1.1.2
