### ISSUE TITLE
Feature request: support adding alt text (descriptions) to images

### ISSUE THREAD

**Issue by jmairboeck** [poetaster/harbour-tooter#38]
Support for adding alt text to images would be good for accessibility.

**Comment by poetaster** [comment]
Yes, it would! I'll have a look. It might be possible with a modification to the warning mechanism.

**Comment by poetaster** [comment]
Hmm, I think this duplicates #9 but I need to check my notes ...

**Comment by poetaster** [comment]
is a dupe of #9
